overblog_graphql:
    definitions:

        # mappings
        auto_mapping: false # use autowiring
        mappings:
            auto_discover: false
            types:
                -
                    type: graphql
                    dir: '%kernel.project_dir%/config/graphql'
                    suffix: ''

        # schemas
        schema:
            movie:
                query: MovieQuery
                #mutation: WidgetMutation
                resolver_maps:
                    - MF\FavoriteMovies\GraphQL\Resolver\MovieResolverMap
